Translate flowcontrol.article, issue #4
golang-ru/tour pull request #7
Opened 2016-09-13 17:34 UTC by DmitriyMV

2016-09-13 17:36 UTC, DmitriyMV commented
Ping issue #4

2016-11-30 02:18 UTC, rumyantseva commented on content/flowcontrol.article
> +Переменные объявленные в этом выражении будут видны только до конца блока `if`.
Пропущены запятые:
```
Переменные, объявленные в этом выражении, будут видны...
```

2016-11-30 02:19 UTC, rumyantseva commented on content/flowcontrol.article
> +Переменные объявленные внутри короткого выражения `if` также доступны внутри
Пропущены запятые:

```
Переменные, объявленные внутри короткого выражения if, также доступны...
```

2016-11-30 02:21 UTC, rumyantseva commented on content/flowcontrol.article
> +Оператор `defer` откладывает вызов функции до момента когда произойдет возврат из
Запятая

```
Оператор defer откладывает вызов функции до момента, когда произойдет возврат...
```

2016-11-30 02:22 UTC, rumyantseva commented on content/flowcontrol.article
> +Вы наверное знали как примерно будет выглядеть `switch`.
Запятые

```
Вы, наверное, знали как примерно будет выглядеть...
```

2016-11-30 02:23 UTC, rumyantseva commented on content/flowcontrol.article
> +Совет: для объявления и инициализации числа с плавающей точкой, используйте синтаксис объявления чисел с плавающей точкой или преобразование:
По-моему, запятая не нужна

```
для объявления и инициализации числа с плавающей точкой используйте синтаксис...
```

2016-11-30 02:25 UTC, rumyantseva commented on content/flowcontrol.article
> +В качестве простой игры с функциями и циклами, напишите функцию получения квадратного корня числа, используя метод Ньютона.
Запятая не нужна:

```
В качестве простой игры с функциями и циклами напишите функцию...
```

2016-11-30 02:25 UTC, rumyantseva commented on content/flowcontrol.article
> +В этом случае, метод Ньютона заключается в аппроксимации `Sqrt(x)` через выбор начальной точки _z_, а затем повторе:
По-моему, запятая не нужна

```
В этом случае метод Ньютона заключается в...
```

2016-11-30 02:26 UTC, rumyantseva commented on content/flowcontrol.article
> +Для начала, повторите вычисление 10 раз и посмотрите как близко вы сможете приблизиться к ответу для различных чисел (1, 2, 3, ...).
Запятые (одна лишняя и одной не хватает):

```
Для начала повторите вычисление 10 раз и посмотрите, как близко вы сможете...
```

2016-11-30 02:27 UTC, rumyantseva commented on content/flowcontrol.article
> +Затем, измените условие цикла, чтобы цикл прекращал свое выполнение сразу, как только значение прекратило изменяться (или изменилось на очень малую величину). Посмотрите как это отразилось на числе и
Лишняя запятая:

```
Затем измените условие цикла, чтобы цикл...
```

И одной запятой не хватает:

```
Посмотрите, как это отразилось на числе итераций.
```

2016-11-30 02:32 UTC, rumyantseva requested changes
Запятые иногда не в тех местах, а по терминологии на мой вкус всё ok.

2017-03-20 11:24 UTC, DmitriyMV commented
ping @rumyantseva  - готово. Долго получилось, я забыть успел про этот пул =)

2017-03-21 02:39 UTC, rumyantseva commented
В общем, я мёржу :)
Если что-то осталось, в рамках финальных правок пофиксим.
Спасибо!

2017-03-21 02:39 UTC, merged